-
  name: Install rbenv
  hosts: target1

  vars:
    # - rbenv_root: /home/deploy/.rbenv/bin
    - ruby_version: 2.5.8

  tasks:
    # - name: Install software-properties-common
    #   apt:
    #     name: software-properties-common
    #     state: present
    #     update_cache: yes
    #   become: yes
    # - name: Add ppa ansible
    #   apt_repository:
    #     repo: ppa:ansible/ansible
    #   become: yes
    # - name: Install ansible
    #   apt:
    #     name: ansible
    #     state: present
    #     update_cache: yes
    #   become: yes
    - name: Update apt cache
      apt:
        update_cache: yes
      become: yes
    - name: Install dependency library
      apt:
        pkg:
        - git
        - curl
        - libssl-dev
        - libreadline-dev
        - zlib1g-dev
        - autoconf
        - bison
        - build-essential
        - libyaml-dev
        - libreadline-dev
        - libncurses5-dev
        - libffi-dev
        - libgdbm-dev
      become: yes
    - name: rbenv | download install shell script
      get_url:
        url: https://github.com/rbenv/rbenv-installer/raw/HEAD/bin/rbenv-installer
        dest: /home/deploy/rbenv-installer.sh
        mode: "0755"
        group: deploy
        owner: deploy
      become: yes
    - name: rbenv | install shell script
      command: bash /home/deploy/rbenv-installer.sh
      become_user: deploy
    - name: setup bash environment
      lineinfile:
        path: /home/deploy/.bashrc
        line: 'export PATH="$HOME/.rbenv/bin:$PATH"'
    - name: rbenv | load automatically
      lineinfile:
        path: /home/deploy/.bashrc
        line: 'eval "$(rbenv init -)"'
    - name: rbenv | check ruby version installed
      shell: /home/deploy/.rbenv/bin/rbenv versions | grep {{ ruby_version }}
      register: ruby_installed
      ignore_errors: true
    - name: rbenv | install ruby 2.5.8
      shell: /home/deploy/.rbenv/bin/rbenv install 2.5.8
      when: ruby_installed.rc == 1
    # - name: print out
    #   debug: msg={{ ruby_installed }}
    # - name: nginx | add nginx ppa repository
      # apt_repository:
        # repo: ppa:nginx/stable
      # become: yes
    - name: nginx | install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes
      become: yes
    # TODO: install passenger module
    # TODO: setup nginx site
